version: "3.9"
services:
    web_apache:
        build:
            context: ./.docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            # connexion SQL
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DBNAME: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

            HOOS_CTF_USERNAME: ${HOOS_CTF_USERNAME:-}

            RETURN_POSSIBLE: ${RETURN_POSSIBLE}
            # Les flags
            FLAG_LEVEL_0: ${FLAG_LEVEL_0}
            FLAG_LEVEL_1: ${FLAG_LEVEL_1}
            FLAG_LEVEL_2: ${FLAG_LEVEL_2}
            FLAG_LEVEL_3: ${FLAG_LEVEL_3}
            FLAG_LEVEL_4: ${FLAG_LEVEL_4}
            FLAG_LEVEL_5: ${FLAG_LEVEL_5}
            FLAG_LEVEL_6: ${FLAG_LEVEL_6}
            # Les flags Bonus
            FLAG_BONUS_WHITE_HAT: ${FLAG_BONUS_WHITE_HAT}
            FLAG_BONUS_CURIEUX: ${FLAG_BONUS_CURIEUX}
            FLAG_BONUS_JOB: ${FLAG_BONUS_JOB}
            # Le FLAG de fin
            FLAG_FINAL: ${FLAG_FINAL}
            
            # Les IPs valide pour Flag 1
            IP_VALID_1: ${IP_VALID_1}
            IP_VALID_2: ${IP_VALID_2}

            # IP DU BOT
            BOT_IP: 172.30.10.80

            # IP DES SERVEURS
            SERVER_WEB: 172.30.10.100
            SERVER_SQL: 172.30.10.101
            SERVER_DOMOTIQUE: 172.30.10.102

            # API KEY
            API_KEY_DOMOTIQUE: ${API_KEY_DOMOTIQUE}
        ports:
            - ${PORT}:80
        restart: always
        labels:
            ho.ctf.cyrhades: "1"
        volumes:
            - web:/var/www/html
            - shared-data:/var/www/html/shared
        networks:
            vivatech_network:
                ipv4_address: 172.30.10.100
    db:
        container_name: sql.vivatech.fr
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./.docker/db/init.sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        networks:
            vivatech_network:
                ipv4_address: 172.30.10.101
        labels:
            ho.ctf.cyrhades: "1"
    api_apache:
        container_name: api.vivatech.fr
        build:
            context: ./.docker/api
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            API_KEY_DOMOTIQUE: ${API_KEY_DOMOTIQUE}        
            LIGHT_HUE: ${LIGHT_HUE}
        restart: always
        networks:
            vivatech_network:
                ipv4_address: 172.30.10.102
        labels:
            ho.ctf.cyrhades: "1"
        volumes:
            - shared-data:/var/www/html/shared
    botserver:
        build: ./.docker/bot/
        restart: always
        container_name: bot.vivatech.fr
        healthcheck:
            test: ["CMD", "wscat", "-c", "ws://localhost:8282"]
            interval: 5s
            timeout: 3s
            retries: 10
        command: npm start
        labels:
            ho.ctf.cyrhades: "1"
        networks:
            vivatech_network:
                ipv4_address: 172.30.10.80
    composer:
        image: composer
        volumes:
            - web:/app
        command: composer install --ignore-platform-reqs
volumes:
    web:
        labels:
            ho.ctf.cyrhades: "1"
    shared-data:
        labels:
            ho.ctf.cyrhades: "1"
networks:
  vivatech_network:
    ipam:
      config:
        - subnet: 172.30.10.0/24